server:
  port: 5000
spring:
  application:
    name: jeekite-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  routes:
    jeekite-sys:
      path: /sys/**
      serviceId: jeekite-sys
  prefix: /api/jeekite

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000