server:
  port: 10010
spring:
  application:
    name: jeekite-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    jeekite-service: /sys/** # 商品微服务的映射路径